# Generated by Django 4.0.4 on 2022-05-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('alsodev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTokenModel',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
